### ISSUE TITLE
The car goes in zig zag way and does not go straight.

### ISSUE THREAD

**Issue by madanmohany** [dmwnz/SimCycling#5]

**Comment by madanmohany** [comment]
Using Box cam 0.7.0 (https://www.racedepartment.com/downloads/box-cam.7268/), I could get a stable camera. So, closing the issue. Thanks.

**Comment by Isnega** [comment]
The same thing happens to me, everything works fine except the turn, the car goes in a zig zag. I saw that you solved it, but I don't understand how you did it. Can you explain to me the steps to follow to create a new vjoy 2 and what data to modify. I attach a photo of the controls and video. Thank you for your response.
